categories = {
    "history": {
        "tourism.sights.memorial", "tourism.sights.memorial.aircraft",
        "tourism.sights.memorial.locomotive", "tourism.sights.memorial.railway_car",
        "tourism.sights.memorial.ship", "tourism.sights.memorial.tank", "tourism.sights.memorial.tomb",
        "tourism.sights.memorial.monument", "tourism.sights.memorial.wayside_cross",
        "tourism.sights.memorial.boundary_stone", "tourism.sights.memorial.pillory",
        "tourism.sights.memorial.milestone", "tourism.sights.place_of_worship",
        "tourism.sights.place_of_worship.church", "tourism.sights.place_of_worship.chapel",
        "tourism.sights.place_of_worship.cathedral", "tourism.sights.place_of_worship.mosque",
        "tourism.sights.place_of_worship.synagogue", "tourism.sights.place_of_worship.temple",
        "tourism.sights.place_of_worship.shrine", "tourism.sights.castle", "tourism.sights.ruines",
        "tourism.sights.archaeological_site", "tourism.sights.fort", "heritage", "heritage.unesco",
        "entertainment.museum", "building.place_of_worship", "building.historic"},
    "architecture": {
        "tourism.sights.place_of_worship",
        "tourism.sights.place_of_worship.church",
        "tourism.sights.place_of_worship.chapel",
        "tourism.sights.place_of_worship.cathedral",
        "tourism.sights.place_of_worship.mosque",
        "tourism.sights.place_of_worship.synagogue",
        "tourism.sights.place_of_worship.temple",
        "tourism.sights.place_of_worship.shrine",
        "tourism.sights.lighthouse",
        "tourism.sights.windmill",
        "tourism.sights.tower",
        "tourism.sights.city_gate",
        "tourism.sights.bridge",
        "tourism.sights.battlefield",
        "tourism.sights.fort",
        "tourism.sights.lighthouse",
        "tourism.sights.windmill",
        "tourism.sights.monastery",
        "tourism.sights.city_hall",
        "tourism.attraction.fountain",
        "tourism.attraction.clock",
        "building.place_of_worship",
        "building.tourism"},
    "art": {
        "tourism.attraction.artwork",
        "entertainment.culture.theatre",
        "entertainment.culture.arts_centre",
        "entertainment.culture.gallery"
    },
    "nature": {
        "natural.forest",
        "natural.water",
        "natural.water.spring",
        "natural.water.reef",
        "natural.water.hot_spring",
        "natural.water.geyser",
        "natural.water.seas",
        "natural.mountain",
        "natural.mountain.peak",
        "natural.mountain.glacier",
        "natural.mountain.cliff",
        "natural.mountain.rock",
        "natural.mountain.cave_entrance",
        "natural.sand",
        "natural.sand.dune",
        "national_park",
        "leisure.park",
        "leisure.park.garden",
        "leisure.park.nature_reserve",
        "leisure.park",
        "leisure.park.garden"
    }
}
